# This workflow will do a clean installation of node dependencies, cache/restore them, build the code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "test/Tests" ]
  pull_request:
    branches: [ "test/Tests" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [serveur]
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./${{ matrix.folder }}/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.folder }}
      
      - name: Run tests
        run: npm test
        working-directory: ${{ matrix.folder }}
        
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
